name: Dependabot auto-merge

on:
  schedule:
    - cron: "34 12 * * *"
  workflow_dispatch:

jobs:
  auto_merge_dependabot_pr:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: snow-actions/git-config-user@v1.0.0
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        name: Fast-forward merge first Dependabot PR
        run: |
          branch=$(gh pr list -R "$REPOSITORY" --json author,headRefName,mergeStateStatus --jq 'map(select(.author.login == "dependabot" and .mergeStateStatus == "CLEAN")) | .[-1].headRefName')
          if [ -n "$branch" ]; then
            git merge --ff-only "origin/$branch"
            git push
          fi
