name: Enforce policies
on:
  - pull_request
jobs:
  conform:
    name: Conform
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - run: git fetch --no-tags origin master:master
      - name: Conform Action
        uses: talos-systems/conform@v0.1.0-alpha.26
