# Terraform Provider release workflow.
name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release-please:
    name: Release Please
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    runs-on: ubuntu-22.04
    steps:
      - id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          bump-minor-pre-major: true
          package-name: terraform-provider-talos
          release-type: go
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
  goreleaser:
    if: ${{ needs.release-please.outputs.release_created }}
    name: GoReleaser
    needs: release-please
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: go.mod
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        id: import_gpg
        with:
          fingerprint: ${{ secrets.GPG_FINGERPRINT }}
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --rm-dist
        env:
          # GitHub sets the GITHUB_TOKEN secret automatically.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
